/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertPopup: typeof import('./src/components/alertPopup.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Badge: typeof import('primevue/badge')['default']
    BlackHoleBackground: typeof import('./src/components/ui/bg-black-hole/BlackHoleBackground.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('./src/components/ui/calendar/Calendar.vue')['default']
    CalendarCell: typeof import('./src/components/ui/calendar/CalendarCell.vue')['default']
    CalendarCellTrigger: typeof import('./src/components/ui/calendar/CalendarCellTrigger.vue')['default']
    CalendarGrid: typeof import('./src/components/ui/calendar/CalendarGrid.vue')['default']
    CalendarGridBody: typeof import('./src/components/ui/calendar/CalendarGridBody.vue')['default']
    CalendarGridHead: typeof import('./src/components/ui/calendar/CalendarGridHead.vue')['default']
    CalendarGridRow: typeof import('./src/components/ui/calendar/CalendarGridRow.vue')['default']
    CalendarHeadCell: typeof import('./src/components/ui/calendar/CalendarHeadCell.vue')['default']
    CalendarHeader: typeof import('./src/components/ui/calendar/CalendarHeader.vue')['default']
    CalendarHeading: typeof import('./src/components/ui/calendar/CalendarHeading.vue')['default']
    CalendarNextButton: typeof import('./src/components/ui/calendar/CalendarNextButton.vue')['default']
    CalendarPrevButton: typeof import('./src/components/ui/calendar/CalendarPrevButton.vue')['default']
    Card: typeof import('primevue/card')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Form: typeof import('@primevue/forms/form')['default']
    IftaLabel: typeof import('primevue/iftalabel')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/siteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/siteHeader.vue')['default']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
  }
}
